"""vault and secure documents

Revision ID: 49fbdc9b92b1
Revises: aa8f3bc254e8
Create Date: 2026-09-26 18:00:29.907969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fbdc9b92b1'
down_revision: Union[str, Sequence[str], None] = 'aa8f3bc254e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vaults',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('kdf_algorithm', sa.String(length=20), nullable=False),
    sa.Column('kdf_salt', sa.String(length=64), nullable=False),
    sa.Column('kdf_ops', sa.Integer(), nullable=False),
    sa.Column('kdf_mem', sa.Integer(), nullable=False),
    sa.Column('encrypted_private_key', sa.String(length=128), nullable=False),
    sa.Column('private_key_nonce', sa.String(length=32), nullable=False),
    sa.Column('recovery_encrypted_private_key', sa.String(length=128), nullable=False),
    sa.Column('recovery_nonce', sa.String(length=32), nullable=False),
    sa.Column('key_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_vaults_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_vaults'))
    )
    op.create_table('project_key_grants',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sealed_key', sa.Text(), nullable=False),
    sa.Column('recipient_public_key', sa.String(length=64), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_project_key_grants_granted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_key_grants_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_key_grants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'key_version', 'user_id', name=op.f('pk_project_key_grants'))
    )
    op.create_index(op.f('ix_project_key_grants_user_id'), 'project_key_grants', ['user_id'], unique=False)
    op.add_column('document_versions', sa.Column('ciphertext', sa.Text(), nullable=True))
    op.add_column('document_versions', sa.Column('nonce', sa.String(length=32), nullable=True))
    op.add_column('document_versions', sa.Column('key_version', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('ciphertext', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('nonce', sa.String(length=32), nullable=True))
    op.add_column('documents', sa.Column('key_version', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('key_version', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('rotation_pending', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'rotation_pending')
    op.drop_column('projects', 'key_version')
    op.drop_column('documents', 'key_version')
    op.drop_column('documents', 'nonce')
    op.drop_column('documents', 'ciphertext')
    op.drop_column('document_versions', 'key_version')
    op.drop_column('document_versions', 'nonce')
    op.drop_column('document_versions', 'ciphertext')
    op.drop_index(op.f('ix_project_key_grants_user_id'), table_name='project_key_grants')
    op.drop_table('project_key_grants')
    op.drop_table('user_vaults')
    # ### end Alembic commands ###
