import type { Schemas } from "@/lib/api"

export type Me = Schemas["Me"]
export type PublicConfig = Schemas["PublicConfig"]
export type SessionInfo = Schemas["SessionOut"]
export type AccountActivity = Schemas["AccountActivity"]
export type WorkspaceSummary = Schemas["WorkspaceSummary"]
export type WorkspaceDetail = Schemas["WorkspaceDetail"]
export type Member = Schemas["MemberOut"]
export type Role = Schemas["RoleOut"]
export type PermissionInfo = Schemas["PermissionInfo"]
export type Invitation = Schemas["InvitationOut"]
export type MyInvitation = Schemas["MyInvitation"]
export type Project = Schemas["ProjectOut"]
export type ProjectMember = Schemas["ProjectMemberOut"]
export type DocumentSummary = Schemas["DocumentSummary"]
export type DocumentFull = Schemas["DocumentOut"]
export type VersionSummary = Schemas["VersionSummary"]
export type Version = Schemas["VersionOut"]
export type Activity = Schemas["ActivityOut"]
export type NotificationItem = Schemas["NotificationOut"]
export type UserRef = Schemas["UserRef"]
export type ThemePreference = Me["theme"]
export type DocKind = DocumentSummary["kind"]
export type DocFormat = DocumentSummary["format"]
